### PR TITLE
Initial Links API implementation.

### PR DESCRIPTION
**Pull request by chakrit**

### CODE REVIEW

**Comment by schumarn** [comment]
👍

**Comment by iporsut** [comment]
I try to `make gen` and found `SearchResult` is in `gen_list.go`.

I think SearchResult should be only base for SearchResult struct like `Base` and `List`.

**Comment by Kanokorn** [comment]
In `context.go` file line 25, I recommend this pattern to set fields in Golang structs

```Go
return &Context{
		Data: job,
		Job:  job,
		Src:  tmplname,
		User: usr.Username,
		Time: time.Now()
	}, nil
```

**Comment by chakrit** [comment]
@iporsut @Kanokorn will refactor in separate PR na.

**Comment by iporsut** [comment]
👍

**Comment by Kanokorn** [comment]
👍

**Pull request merged**
