### PR TITLE
Remove experimental stuff from the generator.

### PR DESCRIPTION
**Pull request by chakrit**
* Don't generate `SearchResultList`
* Remove `ColorString()` stuff
* Remove `/api` package completely.

### CODE REVIEW

**Comment by iporsut** [comment]
Should delete type GenAPITreeJob in internal/generator/jobs.go:35

**Comment by chakrit** [comment]
@iporsut nice catched, it's deleted.

**Comment by iporsut** [comment]
remove unused constant

`OperationsImportPath = "github.com/omise/omise-go/operations"` 

https://github.com/omise/omise-go/pull/8/files#diff-b5552fb9760d320b934c79d47e9dee2dL9

**Comment by iporsut** [comment]
remove logic for class OperationStruct https://github.com/omise/omise-go/pull/8/files#diff-c31f8d599de15efa96187c86a11eef73R68

```Go
for i := 0; i < named.NumMethods(); i++ {
		m := named.Method(i)
		if m.Name() == "Op" {
			return OperationStruct
		}
	}
```

**Comment by iporsut** [comment]
remove `OperationStruct` constant in `internal/generator/class.go`

**Comment by chakrit** [comment]
@iporsut all fixed :)

**Comment by iporsut** [comment]
👍

**Comment by Kanokorn** [comment]
👍

**Pull request merged**
