### PR TITLE
Support BankAccount JP

### PR DESCRIPTION
**Pull request by kyokomi**
Since Omise Japan needed to specify bank_code instead of brand, we added BankAccountJP separately from BankAccount.

### CODE REVIEW

**Comment by iporsut** [comment]
@kyokomi Thank you for your PR. Could you rebase your PR with current master branch I fix some issue of Travis when building PR.

**Comment by iporsut** [comment]
Sorry @kyokomi Please merge it again.

**Comment by kyokomi** [comment]
@iporsut Thank you. Test passed. 🙏

**Comment by iporsut** [comment]
Fixed by this PR https://github.com/omise/omise-go/pull/18

**Pull request closed without merging**
